import type { Metadata } from "next";
import { LegalLayout, Section } from "../_components/legal-layout";

export const metadata: Metadata = {
  title: "Privacy — Helia",
  description: "How Helia handles your data.",
};

/**
 * Placeholder structure. Replace each Section body with the real text
 * generated by Termly or your lawyer. Headings stay; the prose under
 * them is what you swap in.
 */
export default function PrivacyPage() {
  return (
    <LegalLayout title="privacy policy" updated="2026-05-25">
      <p className="rounded-md border border-line bg-muted-bg px-3 py-2 text-xs text-muted">
        Placeholder copy. Generate the production text with Termly or
        equivalent and replace each section below.
      </p>

      <Section heading="who we are">
        <p>
          Helia is operated by [Legal Entity Name], reachable at{" "}
          <a className="text-fg underline" href="mailto:gethelia@protonmail.com">
            gethelia@protonmail.com
          </a>
          .
        </p>
      </Section>

      <Section heading="what we collect">
        <p>
          Account data (email, password hash, workspace name). Conversation
          data (messages sent to the assistant, the assistant's replies, tool
          calls). Usage data (token counts, request timestamps). Cookies for
          authentication only.
        </p>
      </Section>

      <Section heading="what we don't do">
        <p>
          We do not train models on your data. We do not sell your data. We
          do not share conversations across workspaces.
        </p>
      </Section>

      <Section heading="how we use it">
        <p>
          To provide the service: authenticate you, generate replies, enforce
          usage limits. To improve reliability: aggregated, anonymous metrics.
          To bill you on paid plans.
        </p>
      </Section>

      <Section heading="subprocessors">
        <p>
          OpenAI (LLM inference). Resend (transactional email). Neon (Postgres
          database). Railway / Vercel (hosting). Each receives only the data
          required for its function.
        </p>
      </Section>

      <Section heading="your rights">
        <p>
          You can export, edit, or delete your workspace data at any time
          from your settings. EU/UK and California residents have additional
          rights under GDPR / CCPA. Email us to exercise them.
        </p>
      </Section>

      <Section heading="retention">
        <p>
          Account and workspace data is kept while your account is active.
          Conversation history is retained for as long as you keep the
          workspace, or until you delete it. Deleted data is purged within 30
          days.
        </p>
      </Section>

      <Section heading="contact">
        <p>
          Questions about this policy:{" "}
          <a className="text-fg underline" href="mailto:gethelia@protonmail.com">
            gethelia@protonmail.com
          </a>
          .
        </p>
      </Section>
    </LegalLayout>
  );
}
